export type LandingLang = "id" | "en";

export const landingContent = {
  id: {
    nav: {
      home: "Beranda",
      feature: "Fitur",
      package: "Pricing",
      howTo: "Cara Kerja",
      testimony: "Testimoni",
      faq: "FAQ",
      memberLogin: "MEMBER LOGIN",
      memberArea: "Member Area",
      joinNow: "Gabung Sekarang",
      menu: "Menu",
      language: "EN",
    },
    hero: {
      titleTop: "Trading Lebih Tenang",
      titleMiddle: "dengan Robot",
      titleBottom: "Trading Otomatis",
      subtitle: "Biarkan Robot Bekerja,",
      subtitleHighlight: "Anda Fokus Bertumbuh.",
      description:
        "adalah solusi trading otomatis yang membantu Anda menghemat waktu, mengurangi emosi saat trading, dan menjalankan strategi dengan lebih konsisten.",
      primaryCta: "Mulai Uji Coba Gratis",
      secondaryCta: "Lihat Paket",
      badges: [
        "Full Auto Trading",
        "Cocok untuk Pemula & Profesional",
        "Monitoring Real-Time",
        "Support Setup Gratis",
      ],
    },
    sla: [
      {
        title: "24/7",
        caption1: "Robot Aktif",
        caption2: "Bekerja tanpa henti",
        img: "/images/icon-time.png",
      },
      {
        title: "1.000+",
        caption1: "Trader Bergabung",
        caption2: "Bersama CuanHero meraih peluang setiap hari",
        img: "/images/icon-people.png",
      },
      {
        title: "99.9%",
        caption1: "Server Uptime",
        caption2: "Performa stabil & aman untuk trading Anda",
        img: "/images/icon-shield.png",
      },
    ],
    benefits: {
      headingPrefix: "Kenapa Memilih",
      description:
        "CuanHero membantu Anda trading lebih efisien dengan robot otomatis yang bekerja 24 jam, dilengkapi manajemen risiko dan monitoring real-time.",
      items: [
        {
          title: "Algoritma Canggih",
          description: "Teknologi cerdas untuk membaca peluang pasar.",
          icon: "/images/icon-circle-bot.png",
        },
        {
          title: "Risk Management",
          description: "Pengaturan risiko fleksibel untuk menjaga modal.",
          icon: "/images/icon-shield.png",
        },
        {
          title: "Real-Time Monitoring",
          description: "Pantau performa robot secara real-time.",
          icon: "/images/icon-chart-up.png",
        },
        {
          title: "Akses Dari Mana Saja",
          description: "Monitoring akun melalui HP, tablet, atau PC.",
          icon: "/images/icon-world.png",
        },
        {
          title: "Tanpa Profit Sharing",
          description: "Profit 100% milik Anda tanpa bagi hasil.",
          icon: "/images/icon-sharing-money.png",
        },
        {
          title: "Aman & Transparan",
          description: "Tanpa titip dana, Anda pegang kendali penuh.",
          icon: "/images/icon-lock-money.png",
        },
      ],
    },
    packages: {
      heading: "PILIH PAKET YANG SESUAI",
      popular: "Paling Popular",
      items: [
        {
          title: "FREE TRIAL",
          price: "0",
          duration: "24 jam",
          benefits: [
            { item: "Wajib IB", required: true },
            { item: "Gratis VPS", required: true },
            { item: "Tersedia 2 Pilihan EA", required: true },
            { item: "News Info", required: true },
            { item: "Web Control", required: true },
            { item: "Setup Antri Kuota Harian Terbatas", required: true },
          ],
          cta: "Coba Sekarang",
          premium: false,
        },
        {
          title: "BASIC",
          price: "600.000",
          duration: "/30 hari",
          benefits: [
            { item: "Wajib IB", required: true },
            { item: "Gratis VPS", required: true },
            { item: "Tersedia 3 Pilihan EA", required: true },
            { item: "News Info", required: true },
            { item: "Web Control", required: true },
            { item: "Setup Prioritas", required: true },
          ],
          cta: "Mulai Basic",
          premium: false,
        },
        {
          title: "PREMIUM",
          price: "1.500.000",
          duration: "/30 hari",
          benefits: [
            { item: "Tidak Wajib IB", required: false },
            { item: "Gratis VPS", required: true },
            { item: "Tersedia 3 Pilihan EA", required: true },
            { item: "News Info", required: true },
            { item: "Auto News Filter", required: true },
            { item: "Web Control", required: true },
            { item: "Setup Prioritas", required: true },
          ],
          cta: "Mulai Premium",
          premium: true,
        },
      ],
    },
    start: {
      headingPrefix: "Mulai Dalam",
      headingHighlight: "3 Langkah",
      steps: [
        {
          title: "Daftar Paket",
          description: "Pilih paket yang sesuai dengan kebutuhan anda.",
          icon: "/images/step-1.png",
        },
        {
          title: "Hubungkan Akun Trading",
          description: "Tim kami membantu proses setup hingga selesai.",
          icon: "/images/step-2.png",
        },
        {
          title: "Robot Mulai Bekerja",
          description: "Robot trading bekerja 24/7 untuk anda.",
          icon: "/images/step-3.png",
        },
      ],
    },
    testimony: {
      heading: "Apa Kata Mereka",
      previous: "Slide sebelumnya",
      next: "Slide berikutnya",
      items: [
        ["Andi Pratama", "Trader Gold", "Robotnya mudah digunakan dan setup cepat. Saya tidak perlu lagi mantengin chart seharian."],
        ["Rizky Saputra", "Freelancer", "Trading jadi lebih terukur berkat fitur manajemen risiko yang fleksibel."],
        ["Dimas Kurniawan", "Entrepreneur", "Dana tetap berada di akun pribadi saya sehingga terasa lebih aman dan transparan."],
        ["Fajar Nugroho", "Trader Forex", "Cocok untuk yang sibuk bekerja. Robot berjalan otomatis dan tetap bisa dipantau dari HP."],
        ["Budi Santoso", "Investor", "Monitoring mudah, performa stabil, dan semua transaksi terlihat langsung di akun broker."],
        ["Agus Setiawan", "Part Time Trader", "Tidak ada sistem titip dana sehingga saya tetap memiliki kendali penuh atas modal trading."],
        ["Hendra Wijaya", "Trader Gold", "Instalasi dibantu sampai benar-benar siap jalan. Sangat membantu untuk trader yang baru menggunakan EA."],
        ["Rudi Hartono", "Trader Independen", "Fitur monitoring real-time sangat membantu. Saya bisa melihat aktivitas robot kapan saja tanpa harus membuka chart terus-menerus."],
      ],
    },
    faqs: [
      ["Apakah saya harus memantau chart setiap saat?", "Tidak. Robot akan bekerja secara otomatis 24 jam sehingga Anda tidak perlu memantau chart terus-menerus."],
      ["Apakah cocok untuk pemula?", "Ya. CuanHero dirancang agar mudah digunakan baik oleh pemula maupun trader berpengalaman."],
      ["Apakah ada biaya sharing profit?", "Tidak. Seluruh profit trading menjadi milik Anda tanpa biaya bagi hasil."],
      ["Apakah dana saya aman?", "Ya. Tidak ada sistem titip dana. Dana tetap berada di akun broker pribadi Anda dan sepenuhnya berada dalam kendali Anda."],
      ["Apakah saya perlu transfer dana ke CuanHero?", "Tidak. Anda hanya menghubungkan akun trading Anda ke robot tanpa perlu mentransfer dana kepada kami."],
      ["Bagaimana cara memulai?", "Pilih paket yang sesuai, lakukan registrasi, lalu tim kami akan membantu proses setup hingga robot siap digunakan."],
      ["Bisakah saya memantau robot dari HP?", "Ya. Anda dapat memantau aktivitas dan performa trading melalui smartphone, tablet, maupun komputer."],
      ["Apakah robot selalu profit?", "Trading memiliki risiko dan tidak ada sistem yang dapat menjamin keuntungan. Performa akan bergantung pada kondisi pasar dan pengaturan risiko yang digunakan."],
      ["Apakah saya bisa berhenti kapan saja?", "Ya. Anda dapat menghentikan penggunaan robot atau membatalkan langganan sesuai ketentuan paket yang dipilih."],
      ["Apa itu IB (Introducing Broker)?", "IB atau Introducing Broker adalah mitra resmi broker yang membantu mereferensikan trader ke broker tertentu. Sebagai imbalannya, IB dapat menerima komisi dari aktivitas trading tanpa mengurangi saldo atau profit trader."],
    ],
    bottomBanner: {
      heading: "SIAP TRADING LEBIH PRAKTIS?",
      description:
        "Mulai gunakan robot trading CuanHero hari ini dan rasakan kemudahan trading otomatis yang bekerja untuk Anda.",
      primaryCta: "Mulai Free Trial",
      secondaryCta: "Hubungi Kami",
    },
    footer: {
      navigation: "Navigasi",
      contact: "Hubungi Kami",
      risk: "Trading melibatkan risiko.",
      riskNote: "Pastikan Anda memahami risikonya.",
    },
  },
  en: {
    nav: {
      home: "Home",
      feature: "Features",
      package: "Plans",
      howTo: "How It Works",
      testimony: "Testimonials",
      faq: "FAQ",
      memberLogin: "MEMBER LOGIN",
      memberArea: "Member Area",
      joinNow: "Join Now",
      menu: "Menu",
      language: "ID",
    },
    hero: {
      titleTop: "Trade With More Control",
      titleMiddle: "with an Automated",
      titleBottom: "Trading Robot",
      subtitle: "Let the Robot Work,",
      subtitleHighlight: "You Focus on Growth.",
      description:
        "is an automated trading solution that helps you save time, reduce emotional decisions, and run your strategy more consistently.",
      primaryCta: "Start Free Trial",
      secondaryCta: "View Plans",
      badges: [
        "Full Auto Trading",
        "Beginner & Professional Friendly",
        "Real-Time Monitoring",
        "Free Setup Support",
      ],
    },
    sla: [
      {
        title: "24/7",
        caption1: "Active Robot",
        caption2: "Runs continuously",
        img: "/images/icon-time.png",
      },
      {
        title: "1,000+",
        caption1: "Joined Traders",
        caption2: "Finding opportunities with CuanHero every day",
        img: "/images/icon-people.png",
      },
      {
        title: "99.9%",
        caption1: "Server Uptime",
        caption2: "Stable and secure performance for your trading",
        img: "/images/icon-shield.png",
      },
    ],
    benefits: {
      headingPrefix: "Why Choose",
      description:
        "CuanHero helps you trade more efficiently with a 24-hour automated robot, flexible risk management, and real-time monitoring.",
      items: [
        {
          title: "Advanced Algorithm",
          description: "Smart technology built to read market opportunities.",
          icon: "/images/icon-circle-bot.png",
        },
        {
          title: "Risk Management",
          description: "Flexible risk settings to help protect your capital.",
          icon: "/images/icon-shield.png",
        },
        {
          title: "Real-Time Monitoring",
          description: "Track robot performance in real time.",
          icon: "/images/icon-chart-up.png",
        },
        {
          title: "Access Anywhere",
          description: "Monitor your account from phone, tablet, or PC.",
          icon: "/images/icon-world.png",
        },
        {
          title: "No Profit Sharing",
          description: "Your profit is 100% yours.",
          icon: "/images/icon-sharing-money.png",
        },
        {
          title: "Secure & Transparent",
          description: "No fund custody. You stay fully in control.",
          icon: "/images/icon-lock-money.png",
        },
      ],
    },
    packages: {
      heading: "CHOOSE THE RIGHT PLAN",
      popular: "Most Popular",
      items: [
        {
          title: "FREE TRIAL",
          price: "0",
          duration: "24 hours",
          benefits: [
            { item: "IB required", required: true },
            { item: "Free VPS", required: true },
            { item: "2 EA options available", required: true },
            { item: "News Info", required: true },
            { item: "Web Control", required: true },
            { item: "Limited daily setup queue", required: true },
          ],
          cta: "Try Now",
          premium: false,
        },
        {
          title: "BASIC",
          price: "600.000",
          duration: "/30 days",
          benefits: [
            { item: "IB required", required: true },
            { item: "Free VPS", required: true },
            { item: "3 EA options available", required: true },
            { item: "News Info", required: true },
            { item: "Web Control", required: true },
            { item: "Priority setup", required: true },
          ],
          cta: "Start Basic",
          premium: false,
        },
        {
          title: "PREMIUM",
          price: "1.500.000",
          duration: "/30 days",
          benefits: [
            { item: "IB not required", required: false },
            { item: "Free VPS", required: true },
            { item: "3 EA options available", required: true },
            { item: "News Info", required: true },
            { item: "Auto News Filter", required: true },
            { item: "Web Control", required: true },
            { item: "Priority setup", required: true },
          ],
          cta: "Start Premium",
          premium: true,
        },
      ],
    },
    start: {
      headingPrefix: "Start in",
      headingHighlight: "3 Steps",
      steps: [
        {
          title: "Choose a Plan",
          description: "Pick the plan that matches your needs.",
          icon: "/images/step-1.png",
        },
        {
          title: "Connect Trading Account",
          description: "Our team helps you complete the setup.",
          icon: "/images/step-2.png",
        },
        {
          title: "Robot Starts Working",
          description: "The trading robot works for you 24/7.",
          icon: "/images/step-3.png",
        },
      ],
    },
    testimony: {
      heading: "What Traders Say",
      previous: "Previous slide",
      next: "Next slide",
      items: [
        ["Andi Pratama", "Gold Trader", "The robot is easy to use and the setup was quick. I no longer need to watch charts all day."],
        ["Rizky Saputra", "Freelancer", "Trading feels more measurable thanks to the flexible risk management features."],
        ["Dimas Kurniawan", "Entrepreneur", "My funds remain in my own account, so it feels safer and more transparent."],
        ["Fajar Nugroho", "Forex Trader", "Great for busy people. The robot runs automatically and I can monitor it from my phone."],
        ["Budi Santoso", "Investor", "Monitoring is simple, performance is stable, and every transaction is visible in my broker account."],
        ["Agus Setiawan", "Part-Time Trader", "There is no fund custody, so I keep full control over my trading capital."],
        ["Hendra Wijaya", "Gold Trader", "The installation was assisted until everything was ready. Very helpful for traders new to EAs."],
        ["Rudi Hartono", "Independent Trader", "Real-time monitoring is very useful. I can see robot activity anytime without constantly opening charts."],
      ],
    },
    faqs: [
      ["Do I need to watch charts all the time?", "No. The robot runs automatically 24 hours a day, so you do not need to monitor charts continuously."],
      ["Is it suitable for beginners?", "Yes. CuanHero is designed to be easy to use for both beginners and experienced traders."],
      ["Is there any profit sharing fee?", "No. All trading profit belongs to you with no profit-sharing fee."],
      ["Are my funds safe?", "Yes. There is no fund custody. Your funds remain in your personal broker account and stay fully under your control."],
      ["Do I need to transfer funds to CuanHero?", "No. You only connect your trading account to the robot without transferring funds to us."],
      ["How do I get started?", "Choose the right plan, register, and our team will help with setup until the robot is ready to use."],
      ["Can I monitor the robot from my phone?", "Yes. You can monitor trading activity and performance from a smartphone, tablet, or computer."],
      ["Does the robot always make profit?", "Trading involves risk and no system can guarantee profit. Performance depends on market conditions and risk settings."],
      ["Can I stop anytime?", "Yes. You can stop using the robot or cancel your subscription according to the selected plan terms."],
      ["What is an IB (Introducing Broker)?", "An IB, or Introducing Broker, is an official broker partner that refers traders to a specific broker. In return, an IB may receive commission from trading activity without reducing the trader's balance or profit."],
    ],
    bottomBanner: {
      heading: "READY TO TRADE MORE EFFICIENTLY?",
      description:
        "Start using the CuanHero trading robot today and experience automated trading that works for you.",
      primaryCta: "Start Free Trial",
      secondaryCta: "Contact Us",
    },
    footer: {
      navigation: "Navigation",
      contact: "Contact Us",
      risk: "Trading involves risk.",
      riskNote: "Make sure you understand the risks.",
    },
  },
} as const;
