ALTER TABLE `packages` ADD COLUMN `order_number` INTEGER NOT NULL DEFAULT 9999;
ALTER TABLE `expert_advisors` ADD COLUMN `order_number` INTEGER NOT NULL DEFAULT 9999;
ALTER TABLE `servers` ADD COLUMN `order_number` INTEGER NOT NULL DEFAULT 9999;
